version: 0.2

phases:
  install:
    commands:
      - echo Build started on `date`
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket code-pipeline-2019-06-24 --output-template-file outputSamTemplate.yaml
      #- pip install #your package -t .
artifacts:
  #type: zip
  name: outputbuild.zip
  files:
    #- '**/*'
    - samTemplate.yaml
    - outputSamTemplate.yaml
